config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|uk/ do

    devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions"}

    #routes for image creation and deletion
    resources :course_images,  only: [:create, :destroy]
    resources :index_post_images, only: [:create, :destroy]
    resources :gallery_images, only: [:create, :destroy]
    resources :grade_images, only: [:create, :destroy]
    resources :topic_images, only: [:create, :destroy]
    resources :school_info_images, only: [:create, :destroy]
    resources :workshop_images, only: [:create, :destroy]
    


    resources :grades
    resources :courses 
    resources :galleries
    resources :workshops
    resources :school_infos


    #blog post topics
    resources :topics 

    resources :index_posts, only: [:index, :new, :create]
    resources :index_posts, except: [:index, :new, :create]
    #get '*id', to: 'index_posts#show'


    resources :teachers


    get 'about/home'
    get 'about/news'
    get 'about/organization'
    get 'about/history'

    get "/admin", to: "admin#index"
    get "/admin/administrators", to: "admin#administrators"
    get "/admin/courses", to: "admin#courses"
    get "/admin/galleries", to: "admin#galleries"
    get "/admin/general_info", to: "admin#general_info"
    get "/admin/grades", to: "admin#grades"
    get "/admin/index_posts", to: "admin#index_posts"
    get "/admin/news_topics", to: "admin#news_topics"
    get "/admin/workshops", to: "admin#workshops"
    get "/admin/parents", to: "admin#parents"
    get "/admin/posts", to: "admin#posts"
    get "/admin/sponsored_posts", to: "admin#sponsored_posts"
    get "/admin/students", to: "admin#students"
    get "/admin/teachers", to: "admin#teachers"

    post "admin/confirm_user", to: "admin#confirm_user"
    post "admin/freeze_user", to: "admin#freeze_user"
  
    get 'about' => 'welcome#about'
    get 'index' => 'welcome#index'
    get '/' => 'intro#intro'

    root 'welcome#index'

  end

  

  

  

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user

  has_many :topic_images, dependent: :destroy
  accepts_nested_attributes_for :topic_images, allow_destroy: true

  validates :name, length: {minimum: 5}, presence: true
  validates :description, length: {minimum: 15}, presence: true
  validates :user_id, presence: true

  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include AuthorizationsHelper
  before_action :authorize_admin, except: [:show]


  def new
    @topic = Topic.new

  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    if @topic.save
      flash[:notice] = "Topic was saved succesfully."
      redirect_to admin_news_topics_path
    else
      flash.now[:alert] = "Error creating a topic. Please try again."
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @recent_topics = Topic.all.order(created_at: :desc).limit(3)
  end

  def edit
    @topic = Topic.find(params[:id])
    @topic_image = TopicImage.new
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.user_id = current_user.id
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated."
      redirect_to admin_news_topics_path
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted succesfully."
      redirect_to admin_news_topics_path
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end


  private

    def topic_params
      params.require(:topic).permit(:name, :user_id, :category, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
   <% if @topic.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@topic.errors.count, "error") %>.</h4>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end  %>
  <%= form_group_tag(@topic.errors[:name]) do %>
    <%= f.label t('forms.title') %>
    <%= f.text_field :name, class: 'form-control', placeholder: "...title" %>
  <% end %>
  <%= form_group_tag(@topic.errors[:category]) do %>
    <%= f.label t('forms.category') %>
    <%= f.text_field :category, class: 'form-control', placeholder: "...category" %>
  <% end %>
  <%= form_group_tag(@topic.errors[:description]) do %>
    <%= f.label t('forms.description') %>
    <%= f.cktext_area :description, rows: 8, class: 'form-control', placeholder: "..." %>
  <% end %>

  <% if @topic.topic_images.length > 0 %>
    <div class="row">
    <% @topic.topic_images.each do |img_row| %>
        <div class="edit-form-img-thumb">
          <%= link_to "#{t('forms.delete_image')}", topic_image_path(img_row.id), method: :delete, data: {confirm: "Are you Sure?"}%>
          <div class="img-preview-control">
            <img src="<%=img_row.image%>" alt="course image"/>
          </div>
        </div>
    <%   end %>
    </div>
   <% end %>
  <div class="form-group">
   <%= f.submit "#{t('forms.save_topic')}", class: 'btn btn-success save-form-btn' %>
  </div>
<% end %>

app/views/topics/_image_form.html.erb
<div class="image-form">
  <%= form_for @topic_image do |f| %>

  <% if @topic_image.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic_image.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
        <% @topic_image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(@topic_image.errors[:topic_image]) do %>
      <%= f.label t('forms.image') %>
      <%= f.file_field :image, class: "form-image-input" %>
    <% end %>
    <div class="form-group">
      <%= f.button "#{t('forms.save_image')}", class: "btn btn-success", name: 'topic_id', value: @topic.id %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<div class="container general-edit-container">
  <h1 class="text-center"><%= t('forms.editing')%>  "<%=@topic.name%>"</h1>

  <div class="row">
    <%= render partial: 'form', locals: {topic: @topic} %>
  </div>

  <% if @topic.id != nil %>
    <div class="row">
      <h5><%=t('forms.image_uploader')%></h3>
    </div>
    <div class="row">
      <%= render 'image_form', image: @image %>
    </div>
  <% end %>

  <div class="row">
    <div class="form-back-btn">
      <%= link_to "#{t('forms.back')}", admin_news_topics_path %>
    </div>
  </div>

  <div class="strikethrough">
  </div>
</div>
<br>

app/views/topics/index.html.erb
<h1>Topics</h1>
  <div class="row">
    <div class="col-md-8">
      <% @topics.each do |topic| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media=heading">
              <%= link_to(topic.name, topic) %>
            </h4>
            <small>
              <%= topic.description %>
            </small>
          </div>
        </div>
      <% end %>
    </div>
    <% if user_is_authorized_for_topics? %>
      <div class="col-md-4">
        <%= link_to("new Topic", new_topic_path, class: 'btn btn-success') %>
      </div>
    <% end %>
  </div>

app/views/topics/new.html.erb
<div class="container">
  <h1 class="text-center">New "News" Topic</h1>
      <%= render partial: 'form', locals: {topic: @topic} %>
  <div class="row text-center">
    <div class="col">
      <%= link_to "Back", url_for(:back) %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div id="topics-show">
    <div class="topic-bg-image bg-parallax overlay"></div>
    <div id="topic-title">
      <h3 class="text-center"><%=@topic.name%></h3>
      <p class="text-center"><%=time_tag(@topic.created_at)%></p>
      <h5 class="text-center"><%=t('news.author')%>: <%=User.find_by_id(@topic.user_id).name%></p>
    </div>
</div>

<!-- Blog -->
<div id="blog" class="section">

  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!-- main blog -->
      <div id="main" class="col-md-9">
        <!-- blog post -->
        <div class="blog-post">
          <%= raw(@topic.description) %>
        </div>
        <!-- /blog post -->

        <!-- topic gallery -->
        <div class="row">
        <% @topic.topic_images.each_with_index do |data, index| %>
          <% data_id = "pic" + (index+1).to_s %>
          <% data_target = "#" + data_id %>
          <% if (index == 0) %> 
            <div class="col-md-8 col-sm-12 co-xs-12 gal-item">
              <div class="box">
                <a href="#" data-toggle="modal" data-target="<%=data_target%>">
                  <img src="<%= data.image %>">
                </a>
                <div class="gal-main-modal" id="<%= data_id %>" tabindex="-1" role="dialog">
                ` <span class="gal-modal-close">&times;</span>
                    <img class="gal-modal-content"src="<%= data.image %>">
                </div>
            </div>
          </div>             
          <% else %>  
          <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
            <div class="box">
              <a href="#" data-toggle="modal" data-target="<%=data_target%>">
                <img src="<%= data.image %>">
              </a>
              <div class="gal-main-modal" id="<%= data_id %>" tabindex="-1" role="dialog">
              ` <span class="gal-modal-close">&times;</span>
                  <img class="gal-modal-content"src="<%= data.image %>">
              </div>
            </div>
          </div>
          <% end %>
        <% end %>  
        </div>
        <!-- /topic gallery -->

        


        <div class="blog-comments">
          <h3><%=t('news.comments')%></h3>

          <!-- single comment -->
          <div class="media">
            <div class="media-left">
              <img src="./img/avatar.png" alt="">
            </div>
            <div class="media-body">
              <h4 class="media-heading">John Doe</h4>
              <p>Cu his iudico appareat ullamcorper, at mea ignota nostrum. Nonumy argumentum id cum, eos adversarium contentiones id</p>
              <div class="date-reply"><span>Oct 18, 2017 - 4:00AM</span></div>
            </div>
          </div>
          <!-- /single comment -->

          <!-- single comment -->
          <div class="media">
            <div class="media-left">
              <img src="./img/avatar.png" alt="">
            </div>
            <div class="media-body">
              <h4 class="media-heading">John Doe</h4>
              <p>Cu his iudico appareat ullamcorper, at mea ignota nostrum. Nonumy argumentum id cum, eos adversarium contentiones id</p>
              <div class="date-reply"><span>Oct 18, 2017 - 4:00AM</span></div>
            </div>
          </div>
          <!-- /single comment -->
          <!-- blog reply form -->
          <div class="blog-reply-form">
            <h3>Comment</h3>
            <form>
              <div class="form-group">
                <input class="form-control" type="text" name="name" placeholder="Name">
              </div>
              <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email">
              </div>
              <div class="form-group">
                <textarea class="form-control" placeholder="Enter your Message"></textarea>
              </div>
              <button type="submit" class="btn btn-primary"><%=t('news.submit')%></button>
            </form>
          </div>
          <!-- /blog reply form -->
        </div>
        <!-- /blog comments -->
      </div>
      <!-- /main blog -->

      <div id="aside" class="col-md-3">
        <!-- posts widget -->
        <div class="widget posts-widget">
          <h3><%=t('news.recent_news')%></h3>

          <% if @recent_topics.length > 0 %>
          <!-- single posts -->
            <% @recent_topics.each do |topic| %>
              <div class="single-post">
                <a class="single-post-img" href="/<%=locale%>/topics/<%=topic.id%>">
                  <% if topic.topic_images.length > 0 %>
                    <img src="<%=topic.topic_images[0].image%>" alt="topic image">
                  <% else %>
                    <img src="/assets/stock/new_topic.jpg" alt="topic image">
                  <% end %>
                </a>
                <a href="/<%=locale%>/topics/<%=topic.id%>"><%=raw topic.description.truncate(20)%></a>
                <p><small><%=t('news.author')%>: <%=User.find_by_id(topic.user_id).name%>  <%=time_tag(topic.created_at)%></small></p>
              </div>
            <% end %>
          <!-- /single posts -->
          <% end %>
        </div>
        <!-- /posts widget -->
      </div>
      <!-- /aside blog -->

    </div>
    <!-- row -->

  </div>
  <!-- container -->

</div>
<!-- /Blog -->