config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|uk/ do

    devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions"}

    #routes for image creation and deletion
    resources :course_images,  only: [:create, :destroy]
    resources :index_post_images, only: [:create, :destroy]
    resources :gallery_images, only: [:create, :destroy]
    resources :grade_images, only: [:create, :destroy]
    resources :topic_images, only: [:create, :destroy]
    resources :school_info_images, only: [:create, :destroy]
    resources :workshop_images, only: [:create, :destroy]
    


    resources :grades
    resources :courses 
    resources :galleries
    resources :workshops
    resources :school_infos


    #blog post topics
    resources :topics 

    resources :index_posts, only: [:index, :new, :create]
    resources :index_posts, except: [:index, :new, :create]
    #get '*id', to: 'index_posts#show'


    resources :teachers


    get 'about/home'
    get 'about/news'
    get 'about/organization'
    get 'about/history'

    get "/admin", to: "admin#index"
    get "/admin/administrators", to: "admin#administrators"
    get "/admin/courses", to: "admin#courses"
    get "/admin/galleries", to: "admin#galleries"
    get "/admin/general_info", to: "admin#general_info"
    get "/admin/grades", to: "admin#grades"
    get "/admin/index_posts", to: "admin#index_posts"
    get "/admin/news_topics", to: "admin#news_topics"
    get "/admin/workshops", to: "admin#workshops"
    get "/admin/parents", to: "admin#parents"
    get "/admin/posts", to: "admin#posts"
    get "/admin/sponsored_posts", to: "admin#sponsored_posts"
    get "/admin/students", to: "admin#students"
    get "/admin/teachers", to: "admin#teachers"

    post "admin/confirm_user", to: "admin#confirm_user"
    post "admin/freeze_user", to: "admin#freeze_user"
  
    get 'about' => 'welcome#about'
    get 'index' => 'welcome#index'
    get '/' => 'intro#intro'

    root 'welcome#index'

  end

  

  

  

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  

end

app/views/admin/administrators.html.erb
<div class="container admin-table-container">
    <div class="row">
        <h3 class="mx-auto"><%=t('admin.edit_administrators')%></h3>
    <div>
    <table class="table w-100">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th><%=t('admin.control.name')%></th>
            <th><%=t('admin.control.last_name')%></th>
            <th><%=t('admin.control.email')%></th>
            <th>Role</th>
            <th><%=t('admin.control.confirmed')%></th>
            <th><%=t('admin.control.last_sign_in')%></th>
            <th><%=t('admin.control.sign_in_count')%></th>
            <th><%=t('admin.control.confirm_user')%></th>
            <th><%=t('admin.control.delete_user')%></th>
        </tr>
        </thead>
        <% @administrators.each_with_index do |user, index|%>
        <tbody>
        <tr>
            <td scope="row"><%= (index + 1).to_s %></td>
            <td><%= user.name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><%= time_tag(user.confirmed_at) %></td>
            <td><%= time_tag(user.last_sign_in_at) %></td>
            <td><%= user.sign_in_count %></td>
            <% if user.approved %>
                <td><%= button_to "#{t('admin.control.freeze_user')}", {controller: "admin", action: "freeze_user", user_id: user.id}, method: :post, class: "btn btn-warning", data: {confirm: "ARE YOU SURE?"} %></td>
            <% else %>
                <td><%= button_to "#{t('admin.control.confirm')}", {controller: "admin", action: "confirm_user", user_id: user.id}, method: :post, class: "btn btn-warning", data: {confirm: "#{t('admin.control.confirm')}"} %></td>
            <% end %>
            <td><%= button_to "#{t('admin..control.delete')}", {controller: "registrations", action: "destroy", user_id: user.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
        </tr>
        </tbody>
        <% end %>
    </table>
    <div class="row">
        <div class="col back-btn-col">
            <div class="admin-pag-links">
                <%= will_paginate @administrators %>
            </div>
            <div class="admin-back-link">
                <%= link_to "#{t('admin.control.main_admin')}", admin_path %>
            </div>
        </div>
    </div>
</div>

app/views/admin/courses.html.erb
<div class="container admin-container">
    <div class="row">
        <div class="text-center mx-auto">
            <h4><%= t('admin.edit_courses')%></h4>
        </div>
    </div>
    <div class="row">
        <table class="table w-100">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th><%=t('admin.control.title')%></th>
                <th><%=t('admin.control.teacher')%>r</th>
                <th><%=t('admin.control.grade_level')%></th>
                <th><%=t('admin.control.room')%></th> 
                <th><%=t('admin.control.time')%></th>
                <th><%=t('admin.control.pictures')%></th>
                <th><%=t('admin.control.created_at')%></th>
                <th><%=t('admin.control.updated_at')%></th>
                <th><%=t('admin.control.edit')%></th>
                <th><%=t('admin.control.delete')%></th>
            </tr>
            </thead>
            <% @courses.each_with_index do |course, index|%>
            <tbody>
            <tr>
                <td scope="row"><%= (index + 1).to_s %></td>
                <td><%= course.name %></td>
                <td><%= User.find(course.user_id).full_name %></td>
                <td><%= course.grade.level.ordinalize || "" %></td>
                <td><%= course.room || "" %></td>
                <td><%= course.time || "" %></td>
                <td><%= course.course_images.count %></td>
                <td><%= time_tag(course.created_at) %></td>
                <td><%= time_tag(course.updated_at) %></td>
                <td><%= button_to "#{t('admin.control.edit')}", {controller: "courses", action: "edit", id: course.id}, method: :get, class: "btn btn-warning" %></td>
                <td><%= button_to "#{t('admin.control.delete')}", {controller: "courses", action: "destroy", id: course.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>
     <div class="row">
        <div class="text-center mx-auto">
        <%=button_to "#{t('admin.control.new')}", new_course_path, class: "btn btn-success", method: :get %>
    </div>
</div>

app/views/admin/general_info.html.erb
<div class="container">
    <div class="row">
        <div class="text-center mx-auto">
            <h3><%=t('admin.edit_informational_pages')%></h3>
            <%= button_to "#{t('admin.control.new')}", {controller: "school_infos", action: "new"}, method: :get, class: "btn btn-success" %>
        </div>
        <table class="table">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th>School Info Pages</th>
                <th><%=t('admin.control.title')%></th>
                <th><%=t('admin.control.created_at')%></th>
                <th><%=t('admin.control.updated_at')%></th>
                <th><%=t('admin.control.pictures')%></th>
                <th><%=t('admin.control.edit')%></th>
                <th><%=t('admin.control.delete')%></th>

            </tr>
            </thead>
            <% @school_info_pages.each_with_index do |page, index|%>
            <tbody>
            <tr>
                <th scope="row"><%= (index + 1).to_s %></th>
                <td><%= page.page_type %></td>
                <td><%= page.title %></td>
                <td><%= time_tag(page.created_at) %></td>
                <td><%= time_tag(page.updated_at) %></td>
                <td><%= page.school_info_images.length %></td>
                <td><%= button_to "#{t('admin.control.edit')}", {controller: "school_infos", action: "edit", id: page.slug}, method: :get, class: "btn btn-warning" %></td>
                <td><%= button_to "#{t('admin.control.delete')}", {controller: "school_infos", action: "destroy", id: page.slug}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>


</div>

app/views/admin/grades.html.erb
<div class="container admin-table-container">
    <div class="row">
        <h3 class="text-center"><%= t('admin.edit_grades')%></h3>
    </div>
    <div class="row text-center">
        <div class="col">
            <%= button_to "#{t('admin.control.new')}", {controller: "topics", action: "new"}, class: "btn btn-success", method: :get %>
        </div>
    </div>
    <div class="row">
        <table class="table w-100">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th><%=t('admin.control.grade_level')%></th>
                <th><%=t('admin.control.description')%></th>
                <th></th>
                <th></th> 
                <th><%=t('admin.control.pictures')%></th>
                <th><%=t('admin.control.created_at')%></th>
                <th><%=t('admin.control.updated_at')%></th>
                <th><%=t('admin.control.edit')%></th>
                <th><%=t('admin.control.delete')%></th>
            </tr>
            </thead>
            <% @grades.each_with_index do |grade, index|%>
            <tbody>
            <tr>
                <td scope="row"><%= (index + 1).to_s %></td>
                <td><%= grade.level.ordinalize %></td>
                <td><%= raw grade.description.truncate(20) %></td>
                <td></td>
                <td></td>
                <td><%= grade.grade_images.count %></td>
                <td><%= time_tag(grade.created_at) %></td>
                <td><%= time_tag(grade.updated_at) %></td>
                <td><%= button_to "#{t('admin.control.edit')}", {controller: "grades", action: "edit", id: grade.id}, method: :get, class: "btn btn-warning" %></td>
                <td><%= button_to "#{t('admin.control.delete')}", {controller: "grades", action: "destroy", id: grade.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>
     <div class="row">
        <div class="text-center mx-auto">
        <%=button_to "#{t('admin.control.new')}", new_grade_path, class: "btn btn-success", method: :get %>
    </div>
</div>

app/views/admin/index.html.erb
<div class="container admin-index-container">
  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3 class="text-center"><%=t('admin.admin_page')%></h3>
    </div>
  </div>
</div>

<div class="container admin-users-container">
  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12"> 
      <h3 class="text-center"><%=t('admin.users')%></h3>
    </div>
  </div>
  <div class="row">
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_administrators_path do %>
        <%= t('admin.edit_administrators') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_teachers_path do %>
        <%= t('admin.edit_teachers') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_students_path do %>
        <%= t('admin.edit_students') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_parents_path do %>
        <%= t('admin.edit_parents') %>
      <% end %>
    </div>
  </div>
</div>

<div class="container admin-courses-container">

  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3 class="text-center"><%=t('admin.courses_classes_workshops')%></h3>
    </div>
  </div>

  <div class="row">
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_workshops_path do %>
        <%= t('admin.edit_workshops') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_grades_path do %>
        <%= t('admin.edit_grades') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_courses_path do %>
        <%= t('admin.edit_courses') %>
      <% end %>
    </div>
    <div class="col col-lg-3 col-md-3 col-sm-6 col-xs-12">
      <%= link_to admin_posts_path do %>
        <%= t('admin.edit_posts') %>
      <% end %>
    </div>
  </div>

</div>

<div class="container admin-news-container">
  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12">
      <h3 class="text-center"><%=t('admin.news')%></h3>
    </div>
  </div>
  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12">
      <%= link_to admin_news_topics_path do %>
        <%= t('admin.edit_news') %>
      <% end %>
    </div>
  </div>
</div>

<div class="container admin-pages-container">
  <div class="row">
    <div class="col col-lg-12 col-md-12 col-sm-12">
      <h3 class="text-center"><%=t('admin.school_info_pages')%></h3>
    </div>
  </div>
  <div class="row">
    <div class="col col-lg-4 col-md-4 col-sm-6">
      <%= link_to admin_index_posts_path do %>
        <%= t('admin.edit_index_posts') %>
      <% end %>
    </div>
    <div class="col col-lg-4 col-md-4 col-sm-6">
      <%= link_to admin_general_info_path do %>
        <%= t('admin.edit_general_school_info') %>
      <% end %>
    </div>
    <div class="col col-lg-4 col-md-4 col-sm-6">
      <%= link_to admin_sponsored_posts_path do %>
        <%= t('admin.edit_sponsored_posts') %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/index_posts.html.erb
<div class="container">
    <div class="row">
        <div class="text-center mx-auto">
            <h3><%=t('admin.edit_index_posts')%></h3>
            <%= button_to "#{t('admin.control.new')}", {controller: "index_posts", action: "new"}, method: :get, class: "btn btn-success" %>
        </div>
        <table class="table">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th>Site Section</th>
                <th><%=t('admin.control.title')%></th>
                <th><%=t('admin.control.created_at')%></th>
                <th><%=t('admin.control.updated_at')%></th>
                <th><%=t('admin.control.edit')%></th>
                <th><%=t('admin.control.delete')%></th>

            </tr>
            </thead>
            <% @index_posts.each_with_index do |post, index|%>
            <tbody>
            <tr>
                <th scope="row"><%= (index + 1).to_s %></th>
                <td><%= post.page_type %></td>
                <td><%= post.title %></td>
                <td><%= time_tag(post.created_at) %></td>
                <td><%= time_tag(post.updated_at) %></td>
                <td><%= button_to "#{t('admin.control.edit')}", {controller: "index_posts", action: "edit", id: post.slug}, method: :get, class: "btn btn-warning" %></td>
                <td><%= button_to "#{t('admin.control.delete')}", {controller: "index_posts", action: "destroy", id: post.slug}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>


</div>

app/views/admin/news_topics.html.erb
<div class="container admin-table-container">
    <div class="row">
        <h3 class="mx-auto"><%= t('admin.edit_news')%></h3>
    </div>
    <div class="row text-center">
        <div class="col">
            <%= button_to "#{t('admin.control.new')}", {controller: "topics", action: "new"}, class: "btn btn-success", method: :get %>
        </div>
    </div>
    <div class="row">
        <table class="table w-100">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th><%=t('admin.control.title')%></th>
                <th><%=t('admin.control.author')%></th>
                <th></th>
                <th></th> 
                <th><%=t('admin.control.description')%></th>
                <th><%=t('admin.control.pictures')%></th>
                <th><%=t('admin.control.created_at')%></th>
                <th><%=t('admin.control.updated_at')%></th>
                <th><%=t('admin.control.edit')%></th>
                <th><%=t('admin.control.delete')%></th>
            </tr>
            </thead>
            <% @topics.each_with_index do |topic, index|%>
            <tbody>
            <tr>
                <td scope="row"><%= (index + 1).to_s %></td>
                <td><%= topic.name %></td>
                <td><%= User.find(topic.user_id).full_name %></td>
                <td></td>
                <td></td>
                <td><%= raw topic.description.truncate(30) %></td>
                <td><%= topic.topic_images.count %></td>
                <td><%= time_tag(topic.created_at) %></td>
                <td><%= time_tag(topic.updated_at) %></td>
                <td><%= button_to "#{t('admin.control.edit')}", {controller: "topics", action: "edit", id: topic.id}, method: :get, class: "btn btn-warning" %></td>
                <td><%= button_to "#{t('admin.control.delete')}", {controller: "topics", action: "destroy", id: topic.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>
     <div class="row">
        <div class="col back-btn-col">
            <div class="admin-pag-links">
                <%= will_paginate @topics %>
            </div>
            <div class="admin-back-link">
                <%= link_to "#{t('admin.control.main_admin')}", admin_path %>
            </div>
        </div>
    </div>
</div>

app/views/admin/parents.html.erb
<div class="container">
    <div class="row">
    <h3 class="mx-auto"><%=t('admin.edit_parents')%></h3>
    <table class="table w-100">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th><%=t('admin.control.name')%></th>
            <th><%=t('admin.control.last_name')%></th>
            <th><%=t('admin.control.email')%></th>
            <th>Role</th>
            <th><%=t('admin.control.confirmed')%></th>
            <th><%=t('admin.control.last_sign_in')%></th>
            <th><%=t('admin.control.sign_in_count')%></th>
            <th><%=t('admin.control.confirm_user')%></th>
            <th><%=t('admin.control.delete_user')%></th>
        </tr>
        </thead>
        <% @parents.each_with_index do |user, index|%>
        <tbody>
        <tr>
            <td scope="row"><%= (index + 1).to_s %></td>
            <td><%= user.name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><%= time_tag(user.confirmed_at || Date.today) %></td>
            <td><%= time_tag(user.last_sign_in_at || Date.today) %></td>
            <td><%= user.sign_in_count %></td>
            <% if user.approved %>
                <td><%=t('admin.control.user_confirmed')%></td>
            <% else %>
                <td><%= button_to "#{t('admin.control.confirm')}", {controller: "admin", action: "confirm_user", user_id: user.id}, method: :post, class: "btn btn-warning", data: {confirm: "#{t('admin.control.confirm')}"} %></td>
            <% end %>            
            <td><%= button_to "#{t('admin..control.delete')}", {controller: "registrations", action: "destroy", user_id: user.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
        </tr>
        </tbody>
        <% end %>
    </table>
    </div>
</div>

app/views/admin/students.html.erb
<div class="container admin-table-container">
    <div class="row">
    <h3 class="mx-auto">Students</h3>
        <table class="table w-100">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th><%=t('admin.control.name')%></th>
                <th><%=t('admin.control.last_name')%></th>
                <th><%=t('admin.control.email')%></th>
                <th>Role</th>
                <th><%=t('admin.control.confirmed')%></th>
                <th><%=t('admin.control.last_sign_in')%></th>
                <th><%=t('admin.control.sign_in_count')%></th>
                <th><%=t('admin.control.confirm_user')%></th>
                <th><%=t('admin.control.delete_user')%></th>
            </tr>
            </thead>
            <% @students.each_with_index do |user, index|%>
            <tbody>
            <tr>
                <td scope="row"><%= (index + 1).to_s %></td>
                <td><%= user.name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.role %></td>
                <td><%= user.confirmed_at %></td>
                <td><%= user.last_sign_in_at %></td>
                <td><%= user.sign_in_count %></td>
                <% if user.approved %>
                    <td><%=t('admin.control.user_confirmed')%></td>
                <% else %>
                    <td><%= button_to "#{t('admin.control.confirm')}", {controller: "admin", action: "confirm_user", user_id: user.id}, method: :post, class: "btn btn-warning", data: {confirm: "#{t('admin.control.confirm')}"} %></td>
                <% end %> 
                <td><%= button_to "#{t('admin..control.delete')}", {controller: "registrations", action: "destroy", user_id: user.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
            </tr>
            </tbody>
            <% end %>
        </table>
    </div>
    <div class="row">
        <div class="col back-btn-col">
            <div class="admin-pag-links">
                <%= will_paginate @students %>
            </div>
            <div class="admin-back-link">
                <%= link_to "#{t('admin.control.main_admin')}", admin_path %>
            </div>
        </div>
    </div>
</div>

app/views/admin/teachers.html.erb
<div class="container admin-table-container">
    <div class="row">
        <h3 class="mx-auto"><%=t('admin.edit_teachers')%></h3>
    </div>
    <div class="row text-center">
        <div class="col">
            <%= button_to "#{t('admin.control.new')}", {controller: "teachers", action: "new"}, class: "btn btn-success", method: :get %>
        </div>
    </div>
    <table class="table w-100">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th><%=t('admin.control.name')%></th>
            <th><%=t('admin.control.last_name')%></th>
            <th><%=t('admin.control.email')%></th>
            <th>Role</th>
            <th><%=t('admin.control.confirmed')%></th>
            <th><%=t('admin.control.last_sign_in')%></th>
            <th><%=t('admin.control.sign_in_count')%></th>
            <th><%=t('admin.control.confirm_user')%></th>
            <th><%=t('admin.control.delete_user')%></th>
        </tr>
        </thead>
        <% @teachers.each_with_index do |user, index|%>
        <tbody>
        <tr>
            <td scope="row"><%= (index + 1).to_s %></td>
            <td><%= user.name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><%= user.confirmed_at %></td>
            <td><%= user.last_sign_in_at %></td>
            <td><%= user.sign_in_count %></td>
            <% if user.approved %>
                <td><%=t('admin.control.user_confirmed')%></td>
            <% else %>
                <td><%= button_to "#{t('admin.control.confirm')}", {controller: "admin", action: "confirm_user", user_id: user.id}, method: :post, class: "btn btn-warning", data: {confirm: "#{t('admin.control.confirm')}"} %></td>
            <% end %>            
            <td><%= button_to "#{t('admin..control.delete')}", {controller: "registrations", action: "destroy", user_id: user.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
        </tr>
        </tbody>
        <% end %>
    </table>
    <div class="row">
        <div class="col back-btn-col">
            <div class="admin-pag-links">
                <%= will_paginate @teachers %>
            </div>
            <div class="admin-back-link">
                <%= link_to "#{t('admin.control.main_admin')}", admin_path %>
            </div>
        </div>
    </div>
</div>
    

app/views/admin/workshops.html.erb
<div class="container admin-table-container">
    <div class="row">
        <div class="text-center mx-auto">
            <h3><%=t('admin.edit_workshops')%></h3>
        </div>
    </div>
    <div class="row text-center">
        <div class="col">
            <%= button_to "#{t('admin.control.new')}", {controller: "workshops", action: "new"}, class: "btn btn-success", method: :get %>
        </div>
    </div>
    <div class="row">
    <table class="table w-100">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th><%=t('admin.control.title')%></th>
            <th><%=t('admin.control.description')%></th>
            <th><%=t('admin.control.price')%></th>
            <th><%=t('admin.control.instructor')%></th>
            <th><%=t('admin.control.created_at')%></th>
            <th><%=t('admin.control.updated_at')%></th>
            <th></th>
            <th><%=t('admin.control.edit')%></th>
            <th><%=t('admin.control.delete')%></th>
        </tr>
        </thead>
        <% @workshops.each_with_index do |workshop, index|%>
        <tbody>
        <tr>
            <td scope="row"><%= (index + 1).to_s %></td>
            <td><%= workshop.name %></td>
            <td><%= raw workshop.description.truncate(30)%></td>
            <td><%= workshop.price %></td>
            <td><%= workshop.instructor %></td>
            <td><%= time_tag(workshop.created_at)%></td>
            <td><%= time_tag(workshop.updated_at) %></td>
            <td></td>
            <td><%= button_to "#{t('admin.control.edit')}", {controller: "workshops", action: "edit", id: workshop.id}, method: :get, class: "btn btn-warning" %></td>
            <td><%= button_to "#{t('admin.control.delete')}", {controller: "workshops", action: "destroy", id: workshop.id}, method: :delete, class: "btn btn-danger", data: {confirm: "ARE YOU SURE?"} %></td>
        </tr>
        </tbody>
        <% end %>
    </table>
    </div>
    <div class="row">
        <div class="col back-btn-col">
            <div class="admin-pag-links">
                <%= will_paginate @workshops %>
            </div>
            <div class="admin-back-link">
                <%= link_to "#{t('admin.control.main_admin')}", admin_path %>
            </div>
        </div>
    </div>
</div>