config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|uk/ do

    devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions"}

    #routes for image creation and deletion
    resources :course_images,  only: [:create, :destroy]
    resources :index_post_images, only: [:create, :destroy]
    resources :gallery_images, only: [:create, :destroy]
    resources :grade_images, only: [:create, :destroy]
    resources :topic_images, only: [:create, :destroy]
    resources :school_info_images, only: [:create, :destroy]
    resources :workshop_images, only: [:create, :destroy]
    


    resources :grades
    resources :courses 
    resources :galleries
    resources :workshops
    resources :school_infos


    #blog post topics
    resources :topics 

    resources :index_posts, only: [:index, :new, :create]
    resources :index_posts, except: [:index, :new, :create]
    #get '*id', to: 'index_posts#show'


    resources :teachers


    get 'about/home'
    get 'about/news'
    get 'about/organization'
    get 'about/history'

    get "/admin", to: "admin#index"
    get "/admin/administrators", to: "admin#administrators"
    get "/admin/courses", to: "admin#courses"
    get "/admin/galleries", to: "admin#galleries"
    get "/admin/general_info", to: "admin#general_info"
    get "/admin/grades", to: "admin#grades"
    get "/admin/index_posts", to: "admin#index_posts"
    get "/admin/news_topics", to: "admin#news_topics"
    get "/admin/workshops", to: "admin#workshops"
    get "/admin/parents", to: "admin#parents"
    get "/admin/posts", to: "admin#posts"
    get "/admin/sponsored_posts", to: "admin#sponsored_posts"
    get "/admin/students", to: "admin#students"
    get "/admin/teachers", to: "admin#teachers"

    post "admin/confirm_user", to: "admin#confirm_user"
    post "admin/freeze_user", to: "admin#freeze_user"
  
    get 'about' => 'welcome#about'
    get 'index' => 'welcome#index'
    get '/' => 'intro#intro'

    root 'welcome#index'

  end

  

  

  

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  include AuthorizationsHelper
  before_action :authorize_admin, except: [:index, :show]

  def index
    @teachers = User.where(role: 'teacher').paginate(:page => params[:page]).order('last_name ASC')
    @teacher_intro = IndexPost.find_by_slug('about_teachers')

    respond_to do |format|
      format.html 
      format.json { render json: @teachers }
      format.js
    end
  end

  def new 
    @teacher = User.new
  end

  def create
    @teacher = User.new(user_params)

    if (@teacher.password != @teacher.password_confirmation)
      redirect_to new_teacher_path
    end
    @teacher.role = 2
    @teacher.confirmed_at = Time.now.utc
    if (@teacher.save) 
      if params[:user_image]
        @teacher.create_user_image(image: params[:user_image])
      end
      flash[:notice] = "Teacher Was Created"
      redirect_to admin_teachers_path
    else
      flash.now[:alert] = "Error Saving a Teacher"
      render :new
    end
  end



  def show
    @teacher = User.find(params[:id])
    @teachers_courses = @teacher.courses.reorder("time ASC").page(params[:page]).per_page(3)
    respond_to do |format|
      format.html 
      format.json { render json: @teachers_courses }
      format.js
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :last_name, :email, :password, :description,  :password_confirmation, :grade, :user_image)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_teacher_courses.html.erb
<% @teachers_courses.each do |course| %>
    <% course_image = course.course_images[0] %>
    <% grade_level = course.grade.level.ordinalize %>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
        <div class="course">
            <a href="/<%=locale%>/workshops/<%=course.id%>" class="course-img">
                <% if course_image == nil %>
                    <img src="/assets/stock/workshop_stock_photo.jpg" alt="course image">
                <% else %>
                    <img src="<%=course_image.image%>" alt="course image">
                <% end %>
                <i class="course-link-icon fa fa-link"></i>
            </a>
            <a class="course-title text-center" href="/<%=locale%>/courses/<%=course.id%>"><%= course.name %></a>
            <div class="course-details">
                <span class="course-category"><a href="/<%=locale%>/courses/?grade=<%=grade_level%>"><i class="fas fa-chalkboard-teacher"></i> <%=t('teachers.grade_level')%>: <%=grade_level%></a></span>
                <span class="course-price course-free"><span class="course-time"><i class="far fa-clock"></i>: </span><%= course.time %></span>
            </div>
        </div>
    </div>
<% end %> 

<div class="container teachers-show-pagination">
    <%= paginate @teachers_courses, class: "teachers-paginate-links" %>
</div>

app/views/teachers/_teachers.html.erb
<% @teachers.each do |teacher| %>
    <div class="col-lg-4 col-md-6 teacher-card-column">
        <div class="teacher-card">
            <a href="/<%=locale%>/teachers/<%=teacher.id%>">
                <div class="teacher-index-img-holder">
                    <% if @teacher_intro.index_post_images.length > 0 %>
                        <% image_url = teacher.user_image.image %>
                        <img src="<%=image_url%>" class="teacher-index-img" alt="directors picture">
                    <% else %>
                        <img src="/assets/stock/stock_man.jpg" class="teacher-index-img" alt="directors picture">
                    <% end %>
                </div>
            </a>
            <div class="teacher-card-name">
                <a href="/<%=locale%>/teachers/<%=teacher.id%>">
                    <h5><%=teacher.full_name%></h3>
                </a>
            </div>
            <div class="teacher-card-email">
                    <%= mail_to "#{teacher.email}"  do %>
                    <span><i class="far fa-envelope"></i> <%=teacher.email%></span>
                <% end %>
            </div>
            <div class="teacher-card-description">
                <%=raw(teacher.description.truncate(50))%>
                <%=link_to teacher_path(teacher.id) do %>
                    <%=t('teachers.more')%>...
                <% end %>
            </div>  
        </div>
    </div>
<% end %> 

<div class="container teacher-pag-index">
    <%= paginate @teachers, class: "teachers-paginate-links" %>
</div>

app/views/teachers/index.html.erb
<div id="index-teachers-intro">
  <div class="teachers-bg-image bg-parallax overlay"></div>
    <div id="index-teachers-title">
      <h3><%=@teacher_intro.title%></h3>
    </div>
</div>

<div class="container teacher-index-container">
    <div class="row">
        <div class="col directors-message-profile">
            <div class="strikethrough"></div>
            <div class="directors-message-heading">
                <h3><%=t('teachers.directors_message')%></h3>
            </div>
            <div class="directors-img">
                <% if @teacher_intro.index_post_images.length > 0 %>
                    <% image_url = @teacher_intro.index_post_images[0].image %>
                    <img src="<%=image_url%>" class="img" alt="directors picture">
                <% else %>
                    <img src="/assets/stock/stock_man.jpg" class="img" alt="directors picture">
                <% end %>
            </div>  
            <div class="directors-email">
                <%= mail_to "director@ukrschule.org" do %>
                    <i class="far fa-envelope"></i> <span>director@ukrschule.com</span>
                <% end %>
            </div>  
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="directors-message">
                <%= raw(@teacher_intro.description) %>
            </div>
        </div>
    </div>
    <div class="row teacher-index-center-row">
        <div class="col">
            <div class="strikethrough"></div>
            <div class="teacher-logo">
                <i class="fas fa-user-graduate"></i>
            </div>
            <h4 class="text-center"><%=t("teachers.our_teachers")%></h4>
        </div>
    </div>

    <div class="row teacher-index-row" id="all-teachers-render">
        <%= render "teachers/teachers" %>
    </div>

   
</div>


<div class="container teachers-index-back">
    <div class="strikethrough"></div>
    <div class="row">
        <div class="gen-back-btn">
            <%= link_to "/#{locale}/index", class: 'gen-back'  do %>
                <%=t('teachers.home')%>...
            <% end %>
        </div>
    </div>
</div>
 <footer class="navbar nav-footer navbar-expand">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-facebook-square"></i><span class="sr-only">(current)</span></a></li>
        <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-twitter-square"></i><span class="sr-only">(current)</span></a></li>
        <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-instagram"></i><span class="sr-only">(current)</span></a></li>
    </ul>
</footer>

app/views/teachers/index.js.erb
$('#all-teachers-render').html(' <%= escape_javascript(render :partial => "teachers/teachers") %>');

app/views/teachers/new.html.erb
<div class="container">
    <div class="col-md-10">
    <h3>Teacher Registration</h3>
    <%= form_for(@teacher, url: teachers_path) do |f| %>
    <% if @teacher.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@teacher.errors.count, "error") %> Not Saved: </h2>

        <ul>
        <% @teacher.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <%= form_group_tag(@teacher.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "...name" %>
    <% end %>

    <%= form_group_tag(@teacher.errors[:last_name]) do %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control', placeholder: "...last name" %>
    <% end %>


    <%= form_group_tag(@teacher.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
    <% end %>

    <%= form_group_tag(@teacher.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
    <% end %>

    <%= form_group_tag(@teacher.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    <% end %>

    <%= form_group_tag(@teacher.errors[:grade]) do %>
        <%= f.label :grade %>
        <%= f.text_field :grade, class: 'form-control' %>
    <% end %>

    <%= form_group_tag(@teacher.errors[:description]) do %>
        <%= f.label :description %>
        <%= f.cktext_area :description, rows: 20, class: 'form-control', placeholder: "description of a new class" %>
    <% end %>

    <div class="field">
        <%= f.label :user_image %><br>
        <%= f.file_field :user_mage, name: "user_image" %>
    </div>

    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>

    <% end %>
    </div>
</div>

app/views/teachers/show.html.erb
<div class="container teacher-container">
  <div class="row">
    <div class="col-md-6 img">
      <div class="teacher-img">
        <% if @teacher.user_image != nil %>
          <img src="<%=@teacher.user_image.image%>"  alt="" class="img-rounded">
        <% else %>
          <img src="/assets/stock/stock_man.jpg"  alt="" class="img-rounded">
        <% end %>
      </div>
    </div>
    <div class="col-md-6 details">
      <blockquote>
        <h5><%= @teacher.name + " " + @teacher.last_name %></h5>
        <small><cite title="Source Title">Vienna, Austria<i class="icon-map-marker"></i></cite></small>
      </blockquote>
      <p>
        <i class="fas fa-envelope-square"></i> <%= @teacher.email %><br>
        www.ukrschule.com <br>
      </p>
    </div>
  </div>
  <div class="row">
     <div class="col-md-10 offset-md-1">
        <div class="teacher-description">
          <%= raw(@teacher.description) %>
        </div>
     </div>
  </div>
<% if @teachers_courses.length > 0 %>
  <div class="row show-teacher-course">
    <div class="mx-auto teacher-courses-header">
      <h3><%=t('teachers.courses')%></h3>
    </div>
  </div>
  <div class="row" id="teacher-class-row">
   
    <%= render 'teachers/teacher_courses' %>
    
<% end %>  
</div>
</div>
<footer class="navbar nav-footer navbar-expand">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-facebook-square"></i><span class="sr-only">(current)</span></a></li>
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-twitter-square"></i><span class="sr-only">(current)</span></a></li>
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-instagram"></i><span class="sr-only">(current)</span></a></li>
  </ul>
</footer>

app/views/teachers/show.js.erb
jQuery('#teacher-class-row').html(' <%= escape_javascript(render :partial => "teachers/teacher_courses") %>');