config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)", locale: /en|uk/ do

    devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions"}

    #routes for image creation and deletion
    resources :course_images,  only: [:create, :destroy]
    resources :index_post_images, only: [:create, :destroy]
    resources :gallery_images, only: [:create, :destroy]
    resources :grade_images, only: [:create, :destroy]
    resources :topic_images, only: [:create, :destroy]
    resources :school_info_images, only: [:create, :destroy]
    resources :workshop_images, only: [:create, :destroy]
    


    resources :grades
    resources :courses 
    resources :galleries
    resources :workshops
    resources :school_infos


    #blog post topics
    resources :topics 

    resources :index_posts, only: [:index, :new, :create]
    resources :index_posts, except: [:index, :new, :create]
    #get '*id', to: 'index_posts#show'


    resources :teachers


    get 'about/home'
    get 'about/news'
    get 'about/organization'
    get 'about/history'

    get "/admin", to: "admin#index"
    get "/admin/administrators", to: "admin#administrators"
    get "/admin/courses", to: "admin#courses"
    get "/admin/galleries", to: "admin#galleries"
    get "/admin/general_info", to: "admin#general_info"
    get "/admin/grades", to: "admin#grades"
    get "/admin/index_posts", to: "admin#index_posts"
    get "/admin/news_topics", to: "admin#news_topics"
    get "/admin/workshops", to: "admin#workshops"
    get "/admin/parents", to: "admin#parents"
    get "/admin/posts", to: "admin#posts"
    get "/admin/sponsored_posts", to: "admin#sponsored_posts"
    get "/admin/students", to: "admin#students"
    get "/admin/teachers", to: "admin#teachers"

    post "admin/confirm_user", to: "admin#confirm_user"
    post "admin/freeze_user", to: "admin#freeze_user"
  
    get 'about' => 'welcome#about'
    get 'index' => 'welcome#index'
    get '/' => 'intro#intro'

    root 'welcome#index'

  end

  

  

  

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  

end

app/models/index_post.rb
class IndexPost < ApplicationRecord
    has_many :index_post_images, dependent: :destroy

    accepts_nested_attributes_for :index_post_images, allow_destroy: true 
    enum page_type: [:class_schedule, :workshop_schedule, :all_classes, :preschool, :baby_group, 
                     :cost, :about_classes, :about_teachers, :about_us]
    before_validation :generate_slug


    validates :title, presence: true
    validates :description, presence: true
    validates :slug, uniqueness: true, presence: true, exclusion: {in: %w[signup login]}
    validates_uniqueness_of :page_type

    def to_param
        slug # or "#{id}-#{page_type}".parameterize
    end
      
    def generate_slug
        self.slug ||= page_type.parameterize
    end

    

end

app/controllers/index_posts_controller.rb
class IndexPostsController < ApplicationController
  include AuthorizationsHelper
  before_action :authorize_admin, except: [:show]
  before_filter :find_index_post, only: [:show, :edit, :update, :destroy]

  # GET /index_posts
  def index
    @index_posts = IndexPost.all
  end

  # GET /index_posts/1
  def show
    @index_post_images = IndexPostImage.where(index_post_id: @index_post.id)
    puts @index_post_images.length;
  end


  # GET /index_posts/new
  def new
    @index_post = IndexPost.new
  end

  # GET /index_posts/1/edit
  def edit
  end


  # POST /index_posts
  def create
    @index_post = IndexPost.new
    parameters = index_post_params
    @index_post.title = parameters[:title]
    @index_post.description = parameters[:description]
    @index_post.page_type = parameters[:page_type].to_i
    respond_to do |format|
      if @index_post.save
        format.html do 
          flash[:notice] = "index_post Was Saved"
          redirect_to admin_index_posts_path
        end
        format.json do 
          render action: 'index', status: 'created', location: @index_post
        end
      else
        format.html do 
          flash.now[:alert] = 'There was an error in saving the index_post'
          render :new 
        end
        format.json do 
          render json: @index_post.errors, status: :unprocessable_entity 
        end
      end
    end
  end

  # PATCH/PUT /index_posts/1
  def update
    @index_post.title = index_post_params[:title]
    @index_post.description = index_post_params[:description]
    @index_post.page_type = index_post_params[:page_type].to_i

    respond_to do |format|
      if @index_post.save
        if params[:index_post_images]
          params[:index_post_images].each do |image|
              @index_post.index_post_images.create(image: image)
          end
        end
        format.html do 
          flash[:notice] = "Post was Updated Successfully"
          redirect_to admin_index_posts_path
        end
        format.json do 
          render action: 'index', status: 'updated', location: @course
        end
      else  
        format.html do 
          flash.now[:alert] = "Error saving the post"
          render :edit
        end
        format.json do
          render json: @index_post.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /index_posts/1
  def destroy
    @index_post = IndexPost.find(params[:id])
    @index_post.destroy
    redirect_to admin_path, notice: 'Index post was successfully destroyed.'
  end

  private

    # Only allow a trusted parameter "white list" through.
    def index_post_params
      params.require(:index_post).permit(:title, :description, :page_type, index_post_images_attributes: [:image, :index_post_id])
    end

    def find_index_post
      @index_post = IndexPost.find_by_slug!(params[:id].split("/").last)
    end
end

app/helpers/index_posts_helper.rb
module IndexPostsHelper
    def nested_index_post_path(post)
        "/" + (post.ancestors + [post]).map(&:to_param).join("/")
    end
end

app/views/index_posts/_form.html.erb
<%= form_for(@index_post, html: {multipart: true}) do |f| %>
  <% if @index_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@index_post.errors.count, "error") %> prohibited this index_post from being saved:</h2>

      <ul>
      <% @index_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(@index_post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "...title" %>
  <% end %>
  <%= form_group_tag(@index_post.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.cktext_area :description, rows: 20, class: 'form-control', placeholder: "...description" %>
  <% end %>
  <select name="index_post[page_type]" class="form-control">
      <option selected="selected" value=<%=@index_post.read_attribute_before_type_cast(:page_type)%>><%=t("index_page.#{@index_post.slug}")%></option>
      <option value=0><%=t('index_page.class_schedule')%></option>
      <option value=1><%=t('index_page.workshop_schedule')%></option>
      <option value=2><%=t('index_page.1-11_classes')%></option>
      <option value=3><%=t('index_page.preschool')%></option>
      <option value=4><%=t('index_page.babygroup')%></option>
      <option value=5><%=t('index_page.cost')%></option>
      <option value=6><%=t('index_page.about_classes')%></option>
      <option value=7><%=t('index_page.about_teachers')%></option>
      <option value=8><%=t('index_page.about_us')%></option>
 </select>

 <% if @index_post.index_post_images.length > 0 %>
  <% @index_post.index_post_images.each do |img_row| %>
      <%= link_to "Delete", index_post_image_path(img_row.id), method: :delete %>
      <div class="img-preview-control">
        <img src="<%=img_row.image%>" alt="course image"/>
      </div>
  <% end %>
<% end %>

 <%= f.fields_for :image do |ff| %>
    <div class="field">
      <%= ff.label :image %><br>
      <%= ff.file_field :image, multiple: true, name: "index_post_images[]" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success"%>
  </div>
<% end %>

app/views/index_posts/edit.html.erb
<div class="container">
    <h1>Editing : <%=@index_post.title %></h1>

    <%= render 'form', index_post: @index_post %>

    <%= link_to 'Show', @index_post %> |
    <%= link_to 'Back', index_posts_path %>
</div>

app/views/index_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Index Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @index_posts.each do |index_post| %>
      <tr>
        <td><%= link_to 'Show', index_post %></td>
        <td><%= link_to 'Edit', edit_index_post_path(index_post) %></td>
        <td><%= link_to 'Destroy', index_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Index Post', new_index_post_path %>

app/views/index_posts/new.html.erb
<div class="container">
<h1>New Index Post</h1>

    <%= render 'form', index_post: @index_post %>

    <%= link_to 'Back', index_posts_path %>
</div>

app/views/index_posts/show.html.erb
<div id="index-post-intro">
  <div class="index-post-bg-image bg-parallax overlay"></div>
    <div id="index-post-title">
      <h3><%=@index_post.title%></h3>
    </div>
</div>
<div class="container index-post-container">
    <% if @index_post_images.length > 0%>
    <% img_url = @index_post_images[0].image %>
    <h3 class="text-center"><%= t('index_page.schedule')%></h3>
    <div class="row">
        <div class="col-md-6 col-sm-12 co-xs-12 gal-item offset-md-3">
            <div class="box">
                <a href="#" data-toggle="modal" data-target="#index_image">
                    <img src="<%=img_url%>">
                </a>
                <div class="gal-main-modal" id="index_image" tabindex="-1" role="dialog">
                    <span class="gal-modal-close">&times;</span>
                    <img class="gal-modal-content"src="<%= img_url %>">
                </div>
            </div>
        </div>             
    </div>
    <% end %>
    <div class="row">
        <div class="col">
        <%=raw(@index_post.description)%>
        </div>
    </div>

    <% if @index_post_images.length > 1%>
    <div class="row index-post-gal-row">
        <% @index_post_images.drop(1).each_with_index do |data, index| %>
            <% data_id = "pic" + (index+1).to_s %>
            <% data_target = "#" + data_id %>
            <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
                <div class="box">
                    <a href="#" data-toggle="modal" data-target="<%=data_target%>">
                        <img src="<%= data.image %>">
                    </a>
                    <div class="gal-main-modal" id="<%= data_id %>" tabindex="-1" role="dialog">
                `       <span class="gal-modal-close">&times;</span>
                        <img class="gal-modal-content"src="<%= data.image %>">
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <% end %>
     <div class="gen-back-btn">
        <%= link_to :back,  class: 'gen-back'  do %>
            <%=t('galleries.back')%>...
        <% end %>
    </div>
</div>
<div class="container form-container">
    <div class="row index-post-form-row">
        <div class="col">
            <div class="blog-reply-form">
                <h3 class="text-center"><i class="fas fa-envelope"></i>   <%=t('index_page.contact')%></h3>
                <form>
                    <div class="form-group">
                        <input class="form-control" type="text" name="name" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Enter your Message"></textarea>
                    </div>
                        <button type="submit" class="btn btn-primary"><%=t('index_page.write_us')%></button>
                </form>
            </div>
        </div>
    </div>
</div>
<footer class="navbar nav-footer navbar-expand">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-facebook-square"></i><span class="sr-only">(current)</span></a></li>
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-twitter-square"></i><span class="sr-only">(current)</span></a></li>
    <li class="nav-item"><a class="nav-link social-btn" href="#"><i class="fab fa-instagram"></i><span class="sr-only">(current)</span></a></li>
  </ul>
</footer>